name: studymate
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  file_picker: ^8.0.5
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.6
  syncfusion_flutter_pdfviewer: ^20.4.54
flutter:
  uses-material-design: true

  assets:
    - lib/assets/sample.pdf

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/playstore.png"
